=head1 NAME

kas apropos - Displays each help entry containing a keyword string

=head1 SYNOPSIS

kas apropos B<-topic> I<help string>  [B<-help>]

kas a  B<-t> I<help string>  [B<-h>]

=head1 DESCRIPTION

The C<kas apropos> command displays the first line of the online help
entry for any C<kas> command that has the string specified by the B<-topic>
argument in its name or short description.

To display the syntax for a command, use the C<kas help> command.

=head1 OPTIONS

=over 4

=item B<-topic> I<help string>

Specifies the keyword string to match, in lowercase letters
only. If the string is more than a single word, surround it
with double quotes ("") or other delimiters.

=item B<-help>

Prints the online help for this command. All other valid
options are ignored.

=back

=head1 OUTPUT

The first line of a command's online help entry names it and briefly
describes its function. This command displays the first line for any
C<kas> command where the string specified with the B<-topic> argument is
part of the command name or first line.

=head1 EXAMPLES

The following command lists all C<kas> commands that include the word B<key>
in their names or short descriptions:

    kas apropos key
   setkey: set a user's key
   stringtokey: convert a string to a key

=head1 PRIVILEGE REQUIRED

None, and no password is required.

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

Converted from html to pod by Alf Wachsmann <alfw@slac.stanford.edu>, 2003,
and Elizabeth Cassell <e_a_c@mailsnare.net>, 2004,
Stanford Linear Accelerator Center, a department of Stanford University.

=head1 SEE ALSO

L<kas(1)>,
L<kas_help(1)>

=cut
