#!/bin/sh
# $Id: boot-strap-arla,v 1.1 2002/01/14 07:49:17 shadow Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;exit 0; fi

ARLA_RELEASE=${AFSROOT}/stacken.kth.se/ftp/pub/arla/arla-0.34.tar.gz

mkdir src || exit 1
mkdir obj || exit 1

cd src || exit 1
gzip -dc $ARLA_RELEASE | tar xf -
cd ../obj || exit 1
../src/*/configure || exit 1
make || exit 1
cd milko || exit 1
make || exit 1
exit 0
