#!/bin/sh
# $Id: build-emacs-j,v 1.1 2002/01/14 07:49:17 shadow Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
env MAKEFLAGS="-j" $SHELL $SHELLVERBOSE $srcdir/generic-build $AFSROOT/stacken.kth.se/ftp/pub/gnu/emacs/emacs-20.7.tar.gz emacs-20.7
