#!/bin/sh
# $Id$
FS=${FS:-${objdir}/../appl/fs/fs}

${FS} sq . 0
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
test -f /usr/tmp/openafs-1.2.2-src.tar.gz && cp /usr/tmp/openafs-1.2.2-src.tar.gz openafs-1.2.2-src.tar.gz
test -f openafs-1.2.2-src.tar.gz || wget http://www.openafs.org/dl/1.2.2/openafs-1.2.2-src.tar.gz 2>&4
$SHELL $SHELLVERBOSE $srcdir/generic-build openafs-1.2.2-src.tar.gz openafs-1.2.2
openafs-1.2.2/src/finale/translate_et 180480 >& 4
