#!/bin/sh
# $Id: build-emacs,v 1.1 2002/01/22 19:54:40 hartmans Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
$SHELL $SHELLVERBOSE $srcdir/generic-build $AFSROOT/stacken.kth.se/ftp/pub/gnu/emacs/emacs-20.7.tar.gz emacs-20.7
