#!/bin/sh
# $Id: compare-inum-mp,v 1.1 2002/01/22 19:54:40 hartmans Exp $
FS=${FS:-${objdir}/../appl/fs/fs}
${FS} sa . system:anyuser all || exit 1
${FS} mkm root.cell root.cell || exit 1
$objdir/readdir-vs-lstat . || exit 1
$objdir/readdir-vs-lstat root.cell || exit 1
${FS} rmm root.cell || exit 1
