#!/bin/sh
# $Id$
FS=${FS:-${objdir}/../appl/fs/fs}
${FS} sa . system:anyuser all || exit 1
${FS} mkm root.cell root.cell || exit 1
$objdir/readdir-vs-lstat . || exit 1
$objdir/readdir-vs-lstat root.cell || exit 1
${FS} rmm root.cell || exit 1
