#!/bin/sh
# $Id$
cat > foo <<EOF
hej love

ska vi g|ra r{tt nu.
EOF

cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
exit 0
