#!/bin/sh
# $Id: copy-file,v 1.1 2002/01/22 19:54:40 hartmans Exp $
cat > foo <<EOF
hej love

ska vi g|ra r{tt nu.
EOF

cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
exit 0
