#!/bin/sh
# $Id: copy-and-diff-gnu-mirror,v 1.1 2002/01/14 07:49:17 shadow Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
if test "X$LARGE" = "X" ; then echo "Not running large test $0" ;  exit 0 ; fi
original=${1-$AFSROOT/stacken.kth.se/ftp/pub}
(cd $original; tar cvf - gnu) 2>&4 | tar xvf - >&4
find gnu -type f -exec cmp '{}' $original/'{}' \;
