#!/bin/sh
# $Id: copy-file,v 1.1 2002/01/14 07:49:17 shadow Exp $
cat > foo <<EOF
hej love

ska vi g|ra r{tt nu.
EOF

cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
cp foo foo2 || exit 1
exit 0
