#!/bin/sh
# $Id: dd,v 1.1 2002/01/14 07:49:17 shadow Exp $
if test -r /dev/zero; then
  dd if=/dev/zero of=foo bs=1k count=20 >/dev/null 2>/dev/null || exit 1
  rm foo || exit 1
else
  echo "not running dd (you have no /dev/zero)"
fi
