#!/bin/sh
# $Id: deep-tree,v 1.1 2002/01/14 07:49:17 shadow Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;exit 0; fi

mkdir foo && ( cd foo && $SHELL $SHELLVERBOSE ${srcdir}/dir-tree 5 "0 1 2 3 4" )
${objdir}/rm-rf foo
