#!/bin/sh
# $Id: fcachesize-write-file,v 1.1 2002/01/14 07:49:17 shadow Exp $

FS=${FS:-${objdir}/../appl/fs/fs}
SIZE1=`$FS getcache | awk '{ print $8 ; exit }'`
SIZE2=`expr $SIZE1 + 4`
if test -r /dev/zero; then
  dd if=/dev/zero of=../foo bs=1k count=$SIZE2 >/dev/null 2>/dev/null || exit 1
else
  echo "not running dd (you have no /dev/zero)"
fi

exit 0
