#!/bin/sh
# $Id: fcachesize-file-small,v 1.1 2002/01/14 07:49:17 shadow Exp $

FS=${FS:-${objdir}/../appl/fs/fs}
SIZE1=`$FS getcache -b | awk '{ print $4 ; exit }'`
echo foo > foo
SIZE2=`$FS getcache -b | awk '{ print $4 ; exit }'`
test $SIZE2 = `expr $SIZE1 + 4` || exit 1
rm foo
#SIZE3=`$FS getcache -b | awk '{ print $4 ; exit }'`
#test $SIZE3 = $SIZE1 || exit 1

exit 0
