#!/bin/sh
# $Id$
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
netbsd_ftp_mirror=${1-$AFSROOT/stacken.kth.se/ftp/pub/NetBSD/NetBSD-1.4/}
find ${netbsd_ftp_mirror} -type f -exec cat '{}' \; > /dev/null
