#!/bin/sh
# $Id: find-linux,v 1.1 2002/01/14 07:49:17 shadow Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
linux_src=${1-$AFSROOT/pdc.kth.se/src/OS/Linux/}
(cd ${linux_src} ; find . ) >&4
