#!/bin/sh
# $Id: find-and-cat-netbsd,v 1.1 2002/01/22 19:54:41 hartmans Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
netbsd_ftp_mirror=${1-$AFSROOT/stacken.kth.se/ftp/pub/NetBSD/NetBSD-1.4/}
find ${netbsd_ftp_mirror} -type f -exec cat '{}' \; > /dev/null
