#!/bin/sh
# $Id: getdents-and-unlink1,v 1.1 2002/01/14 07:49:17 shadow Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
gzip -dc ${AFSROOT}/stacken.kth.se/ftp/pub/gnu/emacs/emacs-20.7.tar.gz |
tar vxf - >&4 2>&1 || exit 1
cd emacs-20.7 || exit 1
$objdir/kill-softer lisp || exit 1
test -d lisp && exit 1
exit 0
