#!/bin/sh
# $Id: hardlink5,v 1.1 2002/01/22 19:54:41 hartmans Exp $

if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi

FS=${FS:-${objdir}/../appl/fs/fs}

touch file
ln file ../../service/file && exit 1
rm file

