#!/bin/sh
# $Id$
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
for i in 10 20 30 31 40 50 60 70 80 90 100; do
  $objdir/large-dir2 large-dir-$i $i || exit 1
  $objdir/large-dir3 large-dir-$i $i || exit 1
done
