#!/bin/sh
# $Id: many-fetchs,v 1.1 2002/01/14 07:49:17 shadow Exp $

FS=${FS:-${objdir}/../appl/fs/fs}

touch foo

echo "foobar" > foo

for i in `awk 'BEGIN {for(i=0; i < 1000; ++i) printf "%d\n", i}' /dev/null`; do
    ${FS} flush foo
    cat foo > /dev/null || exit 1
done

rm foo