#!/bin/sh
# $Id: many-stores,v 1.1 2002/01/14 07:49:17 shadow Exp $

touch foo

for i in `awk 'BEGIN {for(i=0; i < 1000; ++i) printf "%d\n", i}' /dev/null`; do
    echo "foo$i" >> foo || exit 1
done

rm foo