#!/bin/sh
# $Id: mkdir,v 1.1 2002/01/14 07:49:17 shadow Exp $
mkdir foo || exit 1
echo hej > foo/1 || exit 1
rmdir foo >/dev/null 2>&1 
test -d foo || exit 1
rm -f foo/1 || exit 1
rmdir foo || exit 1
test -d foo && exit 1
exit 0
