#!/bin/sh
# $Id: rename4,v 1.1 2002/01/22 19:54:42 hartmans Exp $
mkdir old_parent new_parent old_parent/victim || exit 1
mv old_parent/victim new_parent || exit 1
test -d old_parent || exit 1
test -d new_parent || exit 1
test -d old_parent/victim && exit 1
test -d new_parent/victim || exit 1
rmdir new_parent/victim new_parent old_parent
