#!/bin/sh
# $Id: rename4,v 1.1 2002/01/14 07:49:18 shadow Exp $
mkdir old_parent new_parent old_parent/victim || exit 1
mv old_parent/victim new_parent || exit 1
test -d old_parent || exit 1
test -d new_parent || exit 1
test -d old_parent/victim && exit 1
test -d new_parent/victim || exit 1
rmdir new_parent/victim new_parent old_parent
