#!/bin/sh
# $Id: rename3,v 1.1 2002/01/14 07:49:18 shadow Exp $
echo foo > foo || exit 1
sed 's/foo/bar/' foo > bar || exit 1
rm foo || exit 1
test -f foo && exit 1
mv bar foo || exit 1
test -f bar && exit 1
test -f foo || exit 1
