#!/bin/sh
# $Id$
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
emacsver=20.7
gzip -dc ${AFSROOT}/stacken.kth.se/ftp/pub/gnu/emacs/emacs-${emacsver}.tar.gz |
tar vxf - >&4 2>&1 || exit 1
find emacs-${emacsver} -size 0 -print | xargs rm || exit 1
find emacs-${emacsver} -print | xargs chmod u+w || exit 1
$objdir/truncate-files emacs-${emacsver} || exit 1
exit 0
