#!/bin/sh
# $Id: run-fsx,v 1.1 2002/01/14 07:49:18 shadow Exp $
FS=${FS:-${objdir}/../appl/fs/fs}

if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
${objdir}/fsx -N 25000 -RW -c 1 fsxtmp

