#!/bin/sh
# $Id: test-gunzip-gnu-mirror,v 1.1 2002/01/14 07:49:18 shadow Exp $
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
original=${1-$AFSROOT/stacken.kth.se/ftp/pub/gnu}
cd $original || exit 1
find . -name '*.gz' -print | while read i; do
  foo=`gunzip --verbose --test $i 2>&1`
  echo $foo >& 4
  case "$foo" in
*not*in*gzip*format*) ;;
*OK*) ;;
*) exit 1 ;;
  esac
done
