#!/bin/sh
# $Id$
if test "X$FAST" != "X" ; then echo "Not running $0" ;  exit 0 ; fi
wget http://www.openafs.org/dl/1.2.2/openafs-1.2.2-src.tar.gz
for i in 1 2 3 4 5 6 7 8 9 10; do
  $objdir/echo-n '.' >&3
  gzip -dc openafs-1.2.2-src.tar.gz | tar xvf - >&4 || exit 1
  rm -rf openafs-1.2.2
done
echo >&3
