#!/bin/csh -f
#
# Make all the package files.
#
# Arguments:
#	Pathname prefix for the wsadmin directory
#

echo ">> Remembering current directory"
set currdir = `pwd`
echo ">>	[$currdir]"
set wsadmin = $1
echo ">> Creating all package files for ${wsadmin}"
echo ">> cd ${wsadmin}/lib"
cd ${wsadmin}/lib
echo ">> rcsupdate"
rcsupdate
echo ">> cd ${wsadmin}/src"
cd ${wsadmin}/src
echo ">> rcsupdate"
rcsupdate
echo ">> Running make system wsadmin=${wsadmin}..."
make system wsadmin=${wsadmin}
echo ">> Returning to original directory, $currdir"
cd $currdir
