=head1 NAME

package_test - Tests the validity of a package configuration file

=head1 SYNOPSIS

=for html
<div class="synopsis">

S<<< B<package_test> <I<config file>> >>>

=for html
</div>

=head1 DESCRIPTION

The B<package_test> command tests the validity of a B<package>
configuration file created when a prototype file is compiled. The command
interpreter prints error messages on the standard output stream.

This command does not use the syntax conventions of the AFS command
suites. Provide the command name in full.

=head1 OPTIONS

=over 4

=item <I<config file>>

Specifies the package configuration file to validate.

=back

=head1 EXAMPLES

The following example tests the validity of the package configuration file
C<staff.sun4x_56>.

   % package_test staff.sun4x_56

=head1 PRIVILEGE REQUIRED

None

=head1 SEE ALSO

L<package(5)>,
L<package(8)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
