=head1 NAME

pts chown - Changes the owner of a Protection Database entry

=head1 SYNOPSIS

B<pts chown -name> <I<group name>>  -owner <I<new owner>> 
[B<-cell> <I<cell name>>]  [B<-noauth>]  [B<-force>]  [B<-help>]

B<pts cho -na> <I<group name>>  B<-o> <I<new owner>>  [B<-c> <I<cell name>>]  [B<-no>]  [B<-f>]  [-h]

=head1 DESCRIPTION

The pts chown command designates the user or group named by the
B<-owner> argument as the owner of the group named by the
B<-name> argument, and records the new owner in the owner field of the
group's Protection Database entry.

In the case of regular groups, this command automatically changes the group
name's owner prefix (the part of the group name before the colon) to
match the new owner. If the new owner is itself a group, then only its
owner prefix, not its complete name, becomes the owner prefix in the new
name. The change to the owner prefix does not propagate to any groups
owned by the group, however. To make the owner prefix of such
group-owned groups reflect the new owning group, use the B<pts rename>
command.

It is not possible to change a user or machine entry's owner from the
default set at creation time, the B<system:administrators>
group.

=head1 CAVEATS

While designating a machine as a group's owner does not cause an
error, it is not recommended. The Protection Server does not extend the
usual privileges of group ownership to users logged onto the machine.

=head1 OPTIONS

=over 4

=item -name

Specifies the current name of the group to which to assign a new
owner.

=item -owner

Names the user or group to become the group's owner.

=item -cell

Names the cell in which to run the command. For more details, see
the introductory B<pts> reference page.

=item -noauth

Assigns the unprivileged identity anonymous to the
issuer. For more details, see the introductory B<pts> reference
page.

=item -force

Enables the command to continue executing as far as possible when errors
or other problems occur, rather than halting execution at the first
error.

=item -help

Prints the online help for this command. All other valid options
are ignored.

=back

=head1 EXAMPLES

The following example changes the owner of the group
B<terry:friends> from the user B<terry> to the user
B<pat>. A side effect is that the group name changes to
B<pat:friends>.

   % pts chown -name terry:friends -owner pat

The following example changes the owner of the group
B<terry:friends> from the user B<terry> to the group
B<pat:buddies>. A side effect is that the group name
changes to B<pat:friends>.

   % pts chown -name terry:friends -owner pat:buddies

=head1 PRIVILEGE REQUIRED

The issuer must belong to the system:administrators group
or currently own the group.

=head1 SEE ALSO

L<pts(1)>,
L<pts_rename(1)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
