=head1 NAME

pts help - Displays the syntax of specified pts commands or lists
functional descriptions for all B<pts> commands

=head1 SYNOPSIS

B<pts help> [B<-topic> <I<help string>>+]  [-help]

B<pts h> [B<-t> <I<help string>>+]  [-h]

=head1 DESCRIPTION

The pts help command displays the complete online help entry
(short description and syntax statement) for each command operation code
specified by the B<-topic> argument. If the B<-topic>
argument is omitted, the output includes the first line (name and short
description) of the online help entry for every B<pts> command.

To list every pts command whose name or short description
includes a specified keyword, use the B<pts apropos> command.

=head1 OPTIONS

=over 4

=item -topic

Indicates each command for which to display the complete online help
entry. Omit the B<pts> part of the command name, providing only
the operation code (for example, specify B<membership>, not B<pts
membership>). If this argument is omitted, the output briefly
describes every B<pts> command.

=item -help

Prints the online help for this command. All other valid options
are ignored.

=back

=head1 OUTPUT

The online help entry for each pts command consists of the
following two or three lines:

=over 4

=item *

The first line names the command and briefly describes its
function.


=item *

The second line lists aliases for the command, if any.


=item *

The final line, which begins with the string C<Usage>, lists the
command's options in the prescribed order. Online help entries use
the same symbols (for example, brackets) as the reference pages in this
document.


=back

=head1 EXAMPLES

The following command displays the online help entry for the pts
membership command:

   % pts help membership
   pts membership:  list membership of a user or group
   aliases: groups
   Usage: pts membership -nameorid <user or group name or id>+ 
   [-cell <cell name>] [-noauth] [-force] [-help]

=head1 PRIVILEGE REQUIRED

None

=head1 SEE ALSO

L<pts(1)>,
L<pts_apropos(1)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
