=head1 NAME

pts listmax - Displays the C<max user id> and C<max group id> counters

=head1 SYNOPSIS

B<pts listmax> [B<-cell> <I<cell name>>]  [B<-noauth>]  [B<-force>]  [-help]

B<pts listm>  [B<-c> <I<cell name>>]  [B<-n>]  [B<-f>]  [-h]

=head1 DESCRIPTION

The pts listmax command displays the values of the C<max user
id> and C<max group id> counters, which the Protection Server
uses to track the AFS user IDs (AFS UIDs) it allocates to new users or
machines, and the AFS group IDs (AFS GIDs) it allocates to new groups,
respectively. When an administrator next issues the B<pts
createuser> command and does not include the B<-id> argument, the
new user or machine receives an AFS UID one greater than the C<max user
id> counter, and when a user issues the B<pts creategroup>
command and does not include the B<-id> argument, the new group
receives an AFS UID one less (more negative) than the C<max group id>
counter.

To reset one or both counters, members of the
B<system:administrators> group can issue the B<pts
setmax> command.

=head1 OPTIONS

=over 4

=item -cell

Names the cell in which to run the command. For more details, see
the introductory B<pts> reference page.

=item -noauth

Assigns the unprivileged identity anonymous to the
issuer. For more details, see the introductory B<pts> reference
page.

=item -force

Enables the command to continue executing as far as possible when errors
or other problems occur, rather than halting execution at the first
error.

=item -help

Prints the online help for this command. All other valid options
are ignored.

=back

=head1 OUTPUT

The command displays the counters in the following format:

   Max user id is I<user_counter> and max group id is I<group_counter>.

=head1 EXAMPLES

The following example displays the output of this command:

   % pts listmax
   Max user name is 1271 and max group id is -382.

=head1 PRIVILEGE REQUIRED

None

=head1 SEE ALSO

L<pts(1)>,
L<pts_setmax(1)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
