=head1 NAME

vos partinfo - Reports the available and total space on a partition

=head1 SYNOPSIS

B<vos partinfo -server> <I<machine name>>  [-partition <I<partition name>>] 
[B<-cell> <I<cell name>>]  [B<-noauth>]  [B<-localauth>]  [B<-verbose>]  [B<-help>]

B<vos p -s> <I<machine name>>  [B<-p> <I<partition name>>]  [-c <I<cell name>>]  
[B<-n>]  [B<-l>]  [B<-v>]  [B<-h>]

=head1 DESCRIPTION

The vos partinfo command reports the amount of space available
and total size on B<either> all of the partitions on the indicated
file server machine (if the B<-partition> argument is omitted)
B<or> the specified partition on that file server machine. The
Volume Location Database (VLDB) is not consulted.

=head1 OPTIONS

=over 4

=item -server

Identifies the file server machine for which to display partition
information. Provide the machine's IP address or its host name
(either fully qualified or using an unambiguous abbreviation). For
details, see the introductory reference page for the B<vos> command
suite.

=item -partition

Identifies which partition on the file server machine specified by the
B<-server> argument for which to display information. Provide
the partition's complete name with preceding slash (for example,
B</vicepa>) or use one of the three acceptable abbreviated
forms. For details, see the introductory reference page for the
B<vos> command suite.

=item -cell

Names the cell in which to run the command. Do not combine this
argument with the B<-localauth> flag. For more details, see the
introductory B<vos> reference page.

=item -noauth

Assigns the unprivileged identity anonymous to the
issuer. Do not combine this flag with the B<-localauth>
flag. For more details, see the introductory B<vos> reference
page.

=item -localauth

Constructs a server ticket using a key from the local
B</usr/afs/etc/KeyFile> file. The B<vos> command
interpreter presents it to the Volume Server and Volume Location Server during
mutual authentication. Do not combine this flag with the
B<-cell> argument or B<-noauth> flag. For more details,
see the introductory B<vos> reference page.

=item -verbose

Produces on the standard output stream a detailed trace of the
command's execution. If this argument is omitted, only warnings
and error messages appear.

=item -help

Prints the online help for this command. All other valid options
are ignored.

=back

=head1 CAVEATS

The partition-related statistics in this command's output do not
always agree with the corresponding values in the output of the standard UNIX
B<df> command. The statistics reported by this command can be
up to five minutes old, because the Cache Manager polls the File Server for
partition information at that frequency. Also, on some operating
systems, the B<df> command's report of partition size includes
reserved space not included in this command's calculation, and so is
likely to be about 10% larger.

=head1 OUTPUT

The output reports the amount of space available and total space for each
specified partition.

=head1 EXAMPLES

The following command displays all partitions on the file server machine
B<fs2.abc.com>.

   % vos partinfo fs2.abc.com
   Free space on partition /vicepa: 27301 K blocks out of total 549197
   Free space on partition /vicepb: 13646 K blocks out of total 69194
   Free space on partition /vicepc: 31798 K blocks out of total 320315
   Free space on partition /vicepd: 33302 K blocks out of total 494954

=head1 PRIVILEGE REQUIRED

None

=head1 SEE ALSO

L<vos(1)>,
L<vos_listpart(1)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
