#!/bin/csh -fe
# Copyright 2000, International Business Machines Corporation and others.
# All Rights Reserved.
# 
# This software has been released under the terms of the IBM Public
# License.  For details, see the LICENSE file in the top-level source
# directory or online at http://www.openafs.org/dl/license10.html

alias pi ./pinstall
alias ex 'if ( ! (-f \!:*) ) exit ( { echo \!:* failed } )'
rm -rf testdir

pi Makefile testdir
ex testdir/Makefile
pi Makefile testdir
ex testdir/Makefile
rm -rf testdir

pi Makefile testdir/Makefile
ex testdir/Makefile
pi Makefile testdir/Makefile
ex testdir/Makefile
rm -rf testdir

pi -f Makefile testdir/install
ex testdir/install
rm -rf testdir

pi install.c testdir/foo.c
ex testdir/foo.c
pi install.c testdir/c
ex testdir/c/install.c
rm -rf testdir
