#!/usr/bin/perl
#
# Written by Jason Edgecombe based on the Test::Pod documentation.  The
# best way to run it is to run:
#
#     prove check-pod
#
# from the doc/man-pages directory, which will show any errors found in
# any of the POD files.
#
# Extended by Davor Ocelic to support explicit list of POD files or
# sections to check:
#
#     check-pod pod1/fs.pod
#     check-pod pod5
#     check-pod pod1 pod8/volserver.pod
#

use strict;
use Test::More;
eval "use Test::Pod 1.00";

plan skip_all => "Test::Pod 1.00 required for testing POD" if $@;
my @poddirs = qw( pod1 pod3 pod5 pod8 );

my @list;
for ( @ARGV ? @ARGV : @poddirs ) {
	if ( -f ) {
		push @list, $_
	} elsif ( -d ) {
		push @list, grep { !m,fragments/, } all_pod_files( $_ )
	}
}

all_pod_files_ok( @list );
