#!/usr/bin/perl
#
# Written by Jason Edgecombe based on the Test::Pod documentation.  Run
# it to syntax-check all of the POD files.

use strict;
use Test::More;
eval "use Test::Pod 1.00";

plan skip_all => "Test::Pod 1.00 required for testing POD" if $@;
my @poddirs = qw( pod1 pod5 pod8 );
all_pod_files_ok( all_pod_files( @poddirs ) );
