#!/bin/sh -e


# This script reads in  a set of lines in the form
# destination sources
# andmoves sources to destination
# destination is relative to the debian directory

while read dest srcs ; do
    mkdir -p debian/$dest ||true
    for foo in $srcs; do
	cp -rp  dest/$foo debian/$dest
	    done
done
