There are two strategies the File Server can use for attaching AFS volumes
at startup and handling volume salvages.  The traditional method assumes
all volumes are salvaged before the File Server starts and attaches all
volumes at start before serving files.  The newer demand-attach method
attaches volumes only on demand, salvaging them at that time as needed,
and detaches volumes that are not in use.  A demand-attach File Server can
also save state to disk for faster restarts. The B<dafileserver> implements
the demand-attach method, while B<fileserver> uses the traditional method.

The choice of traditional or demand-attach File Server changes the
required setup in F<BosConfig>. When changing from a traditional File
Server to demand-attach or vice versa, you will need to stop and remove
the C<fs> or C<dafs> node in F<BosConfig> and create a new node of the
appropriate type. See L<bos_create(8)> for more information.

Do not use the B<-w> argument, which is intended for use
by the OpenAFS developers only. Changing it from its default
values can result in unpredictable File Server behavior.

Do not specify both the B<-spare> and B<-pctspare> arguments. Doing so
causes the File Server to exit, leaving an error message in the
F</usr/afs/logs/FileLog> file.

Options that are available only on some system types, such as the B<-m>
and B<-lock> options, appear in the output generated by the B<-help>
option only on the relevant system type.

Currently, the maximum size of a volume quota is 2 terabytes (2^41 bytes)
and the maximum size of a /vicepX partition on a fileserver is 2^64
kilobytes. The maximum partition size in releases 1.4.7 and earlier is
2 terabytes (2^31 bytes). The maximum partition size for 1.5.x
releases 1.5.34 and earlier is 2 terabytes as well.

The maximum number of directory entries is 64,000 if all of the entries
have names that are 15 octets or less in length. A name that is 15 octets
long requires the use of only one block in the directory. Additional
sequential blocks are required to store entries with names that are longer
than 15 octets. Each additional block provides an additional length of 32
octets for the name of the entry. Note that if file names use an encoding
like UTF-8, a single character may be encoded into multiple octets.

In real world use, the maximum number of objects in an AFS directory
is usually between 16,000 and 25,000, depending on the average name
length.
