# Copyright 2006-2007, Sine Nomine Associates and others.
# All Rights Reserved.
# 
# This software has been released under the terms of the IBM Public
# License.  For details, see the LICENSE file in the top-level source
# directory or online at http://www.openafs.org/dl/license10.html


# build common variable interfaces
LIBAFSAUTHENT_CFLAGS = \
	$(LIBAFSAUTHENT_CFLAGS_COMMON) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BULDING_MODE)) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BUILDING)) \
	$(NULL)
LIBAFSAUTHENT_OBJS = \
	$(LIBAFSAUTHENT_OBJS_COMMON) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING)) \
	$(NULL)
LIBAFSAUTHENT_OS_CFLAGS = \
	$(LIBAFSAUTHENT_OS_CFLAGS_COMMON) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING_MODE)) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING)) \
	$(NULL)
LIBAFSAUTHENT_OS_OBJS = \
	$(LIBAFSAUTHENT_OS_OBJS_COMMON) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING)) \
	$(NULL)


LIBAFSAUTHENT_BIT_CFLAGS = \
	$(LIBAFSAUTHENT_CFLAGS_COMMON_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(NULL)
LIBAFSAUTHENT_BIT_OBJS = \
	$(LIBAFSAUTHENT_OBJS_COMMON_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(NULL)
LIBAFSAUTHENT_OS_BIT_CFLAGS = \
	$(LIBAFSAUTHENT_OS_CFLAGS_COMMON_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(NULL)
LIBAFSAUTHENT_OS_BIT_OBJS = \
	$(LIBAFSAUTHENT_OS_OBJS_COMMON_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_BIT)) \
	$(NULL)


LIBAFSAUTHENT_INST_CFLAGS = \
	$(LIBAFSAUTHENT_CFLAGS_COMMON_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(NULL)
LIBAFSAUTHENT_INST_OBJS = \
	$(LIBAFSAUTHENT_OBJS_COMMON_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(NULL)
LIBAFSAUTHENT_OS_INST_CFLAGS = \
	$(LIBAFSAUTHENT_OS_CFLAGS_COMMON_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(NULL)
LIBAFSAUTHENT_OS_INST_OBJS = \
	$(LIBAFSAUTHENT_OS_OBJS_COMMON_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(NULL)

LIBAFSAUTHENT_THR_CFLAGS = \
	$(LIBAFSAUTHENT_CFLAGS_COMMON_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(NULL)
LIBAFSAUTHENT_THR_OBJS = \
	$(LIBAFSAUTHENT_OBJS_COMMON_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(NULL)
LIBAFSAUTHENT_OS_THR_CFLAGS = \
	$(LIBAFSAUTHENT_OS_CFLAGS_COMMON_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(NULL)
LIBAFSAUTHENT_OS_THR_OBJS = \
	$(LIBAFSAUTHENT_OS_OBJS_COMMON_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_THR)) \
	$(NULL)

LIBAFSAUTHENT_LIB_CFLAGS = \
	$(LIBAFSAUTHENT_CFLAGS_COMMON_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(LIBAFSAUTHENT_CFLAGS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(NULL)
LIBAFSAUTHENT_LIB_OBJS = \
	$(LIBAFSAUTHENT_OBJS_COMMON_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(LIBAFSAUTHENT_OBJS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(NULL)
LIBAFSAUTHENT_OS_LIB_CFLAGS = \
	$(LIBAFSAUTHENT_OS_CFLAGS_COMMON_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(LIBAFSAUTHENT_OS_CFLAGS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(NULL)
LIBAFSAUTHENT_OS_LIB_OBJS = \
	$(LIBAFSAUTHENT_OS_OBJS_COMMON_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING_MODE)_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(LIBAFSAUTHENT_OS_OBJS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_LIB)) \
	$(NULL)



# final build targets
LIBAFSAUTHENT_ALL_OBJS = \
	$(LIBAFSAUTHENT_OBJS) \
	$(LIBAFSAUTHENT_OS_OBJS) \
	$(LIBAFSAUTHENT_BIT_OBJS) \
	$(LIBAFSAUTHENT_OS_BIT_OBJS) \
	$(LIBAFSAUTHENT_INST_OBJS) \
	$(LIBAFSAUTHENT_OS_INST_OBJS) \
	$(LIBAFSAUTHENT_THR_OBJS) \
	$(LIBAFSAUTHENT_OS_THR_OBJS) \
	$(LIBAFSAUTHENT_LIB_OBJS) \
	$(LIBAFSAUTHENT_OS_LIB_OBJS) \
	$(NULL)

LIBAFSAUTHENT_ALL_CFLAGS = \
	$(LIBAFSAUTHENT_CFLAGS) \
	$(LIBAFSAUTHENT_OS_CFLAGS) \
	$(LIBAFSAUTHENT_BIT_CFLAGS) \
	$(LIBAFSAUTHENT_OS_BIT_CFLAGS) \
	$(LIBAFSAUTHENT_INST_CFLAGS) \
	$(LIBAFSAUTHENT_OS_INST_CFLAGS) \
	$(LIBAFSAUTHENT_THR_CFLAGS) \
	$(LIBAFSAUTHENT_OS_THR_CFLAGS) \
	$(LIBAFSAUTHENT_LIB_CFLAGS) \
	$(LIBAFSAUTHENT_OS_LIB_CFLAGS) \
	$(NULL)

LIBAFSAUTHENT_DEPS = \
	$(LIBAFSAUTHENT_DEPS_$(LIBAFSAUTHENT_BUILDING)_$(LIBAFSAUTHENT_BUILDING_LIB)_$(LIBAFSAUTHENT_BUILDING_THR)_$(LIBAFSAUTHENT_BUILDING_INST)) \
	$(NULL)
