/*
This file was autogenerated from:
    c:\work\pismere\athena\auth\krb5\src\windows\identity\config\csvschema.cfg
    afsconfig.csv

Do not modify directly.
*/
#include<kconfig.h>

kconf_schema schema_afsconfig[] = {
{L"AfsCred",KC_SPACE,0,L"AFS Credentials Provider"},
{L"Module",KC_STRING,(khm_int64) L"OpenAFS",L""},
{L"Description",KC_STRING,(khm_int64) L"AFS Credentials Provider",L""},
{L"Dependencies",KC_STRING,(khm_int64) L"Krb5Cred",L""},
{L"Type",KC_INT32,1,L""},
{L"Flags",KC_INT32,0,L""},
{L"Cells",KC_STRING,(khm_int64) L"",L"Multi string giving list of cells to authenticate to"},
{L"Disableafscreds",KC_INT32,0,L"Disable afscreds.exe"},
{L"Parameters",KC_SPACE,0,L"Parameters for AfsCred"},
{L"AFSEnabled",KC_INT32,1,L"Is AFS enabled?"},
{L"LRUCells",KC_STRING,(khm_int64) L"",L"List of recently used cells"},
{L"LRURealms",KC_STRING,(khm_int64) L"",L"List of recently used realms"},
{L"DefaultCells",KC_STRING,(khm_int64) L"",L"List of default cells to authenticate to."},
{L"Parameters",KC_ENDSPACE,0,L""},
{L"Cells",KC_SPACE,0,L"Per identity cells list and plugin settings"},
{L"cellname",KC_STRING,(khm_int64) L"identity",L"Cell-identity mapping kept in the plugin configuration for the user."},
{L"_Schema",KC_SPACE,0,L"Schema is named for each cell to authenticate"},
{L"MethodName",KC_STRING,(khm_int64) L"",L"Name of method"},
{L"Method",KC_INT32,0,L"(Deprecated) Method identifier"},
{L"Realm",KC_STRING,(khm_int64) L"",L"Kerberos realm to use for authentication"},
{L"_Schema",KC_ENDSPACE,0,L""},
{L"Cells",KC_ENDSPACE,0,L""},
{L"AfsCred",KC_ENDSPACE,0,L""}
};


