=head1 NAME

bos listusers - Lists the privileged users from the UserList file

=head1 SYNOPSIS

B<bos listusers> B<-server> <I<machine name>> [B<-cell> <I<cell name>>]
    [B<-noauth>] [B<-localauth>] [B<-help>]

B<bos listu> B<-s> <I<machine name>> [B<-c> <I<cell name>>] [B<-n>]
    [B<-l>] [B<-h>]

=head1 DESCRIPTION

The B<bos listusers> command lists the user names from the
F</usr/afs/etc/UserList> file on the file server machine named by the
B<-server> argument. The users are authorized to issue privileged B<bos>
and B<vos> commands.

To edit the list of users, use the B<bos adduser> and B<bos removeuser>
commands.

=head1 OPTIONS

=over 4

=item B<-server> <I<machine name>>

Indicates the server machine from which to display the UserList
file. Identify the machine by IP address or its host name (either
fully-qualified or abbreviated unambiguously). For details, see L<bos(8)>.

For consistent performance in the cell, the output must be the same on
every server machine. The B<bos adduser> reference page explains how to
keep the machines synchronized.

=item B<-cell> <I<cell name>>

Names the cell in which to run the command. Do not combine this argument
with the B<-localauth> flag. For more details, see L<bos(8)>.

=item B<-noauth>

Assigns the unprivileged identity C<anonymous> to the issuer. Do not
combine this flag with the B<-localauth> flag. For more details, see
L<bos(8)>.

=item B<-localauth>

Constructs a server ticket using a key from the local
F</usr/afs/etc/KeyFile> file. The B<bos> command interpreter presents the
ticket to the BOS Server during mutual authentication. Do not combine this
flag with the B<-cell> or B<-noauth> options. For more details, see
L<bos(8)>.

=item B<-help>

Prints the online help for this command. All other valid options are
ignored.

=back

=head1 OUTPUT

The output lists the user name of each user entitled to issue privileged
B<bos> and B<vos> commands.

=head1 EXAMPLES

The following example lists the users from UserList file on the machine
C<fs4.abc.com>.

   % bos listusers fs4.abc.com
   SUsers are: pat smith jones terry

=head1 PRIVILEGE REQUIRED

None

=head1 SEE ALSO

L<KeyFile(5)>,
L<UserList(5)>,
L<bos(8)>,
L<bos_adduser(8)>,
L<bos_removeuser(8)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
