=head1 NAME

bos uninstall - Reverts to the former version of a process's binary file

=head1 SYNOPSIS

B<bos uninstall> B<-server> <I<machine name>>
    B<-file> <I<files to uninstall>>+ [B<-dir> <I<destination dir>>]
    [B<-cell> <I<cell name>>] [B<-noauth>] [B<-localauth>] [B<-help>]

B<bos u> B<-s> <I<machine name>> B<-f> <I<files to uninstall>>+
    [B<-d> <I<destination dir>>] [B<-c> <I<cell name>>] [B<-n>] [B<-l>]
    [B<-h>]

=head1 DESCRIPTION

The B<bos uninstall> command replaces each binary file specified by the
B<-file> argument with its C<.BAK> version on the server machine named by
the B<-server> argument, which is normally the binary distribution machine
for its CPU/operating system type. It also changes the extension on the
current C<.OLD> version (if any) to C<.BAK>. Each binary file must reside
in the local F</usr/afs/bin> directory unless the B<-dir> argument names
an alternate directory.

To start using the reverted binary immediately, issue the B<bos restart>
command. Otherwise, the BOS Server automatically restarts the process at
the time defined in the F</usr/afs/local/BosConfig> file; use the B<bos
getrestart> command to display the time and the B<bos setrestart> time to
set it.

=head1 OPTIONS

=over 4

=item B<-server> <I<machine name>>

Indicates the binary distribution machine on which to revert to the
C<.BAK> version of binaries. Identify the machine by IP address or its
host name (either fully-qualified or abbreviated unambiguously). For
details, see L<bos(8)>.

If the machine is not a binary distribution machine and is running an
C<upclientbin> process, then the files are overwritten the next time the
C<upclientbin> process fetches the corresponding file from the
distribution machine (by default within five minutes).

=item B<-file> <I<files to uninstall>>+

Names each binary file to replace with its C<.BAK> version.

=item B<-dir> <I<destinatino dir>>

Provides the complete pathname of the local disk directory containing each
file named by the B<-file> argument. It is necessary only if the binaries
are not in the F</usr/afs/bin> directory.

=item B<-cell> <I<cell name>>

Names the cell in which to run the command. Do not combine this argument
with the B<-localauth> flag. For more details, see L<bos(8)>.

=item B<-noauth>

Assigns the unprivileged identity C<anonymous> to the issuer. Do not
combine this flag with the B<-localauth> flag. For more details, see
L<bos(8)>.

=item B<-localauth>

Constructs a server ticket using a key from the local
F</usr/afs/etc/KeyFile> file. The B<bos> command interpreter presents the
ticket to the BOS Server during mutual authentication. Do not combine this
flag with the B<-cell> or B<-noauth> options. For more details, see
L<bos(8)>.

=item B<-help>

Prints the online help for this command. All other valid options are
ignored.

=back

=head1 EXAMPLES

The following example command overwrites the F</usr/afs/bin/kaserver> file
on the machine C<fs4.abc.com> with its C<.BAK> version, and the current
C<.BAK> version by the C<.OLD> version.

   % bos uninstall -server fs4.abc.com -file kaserver

=head1 PRIVILEGE REQUIRED

The issuer must be listed in the F</usr/afs/etc/UserList> file on the
machine named by the B<-server> argument, or must be logged onto a server
machine as the local superuser C<root> if the B<-localauth> flag is
included.

=head1 SEE ALSO

L<BosConfig(5)>,
L<KeyFile(5)>,
L<UserList(5)>,
L<bos(8)>,
L<bos_getrestart(8)>,
L<bos_restart(8)>,
L<bos_setrestart(8)>,
L<upclient(8)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
