=head1 NAME

bos removehost - Removes a database server machine from the CellServDB file

=head1 SYNOPSIS

=for html
<div class="synopsis">

B<bos removehost> S<<< B<-server> <I<machine name>> >>> S<<< B<-host> <I<host name>>+ >>>
    S<<< [B<-cell> <I<cell name>>] >>> [B<-noauth>] [B<-localauth>] [B<-help>]

B<bos removeh> S<<< B<-s> <I<machine name>> >>> S<<< B<-ho> <I<host name>>+ >>>
    S<<< [B<-c> <I<cell name>>] >>> [B<-n>] [B<-l>] [B<-he>]

=for html
</div>

=head1 DESCRIPTION

The B<bos removehost> command removes the entry for each database server
machine specified with the B<-host> argument from the
F</usr/afs/etc/CellServDB> file on the server machine named by the
B<-server> argument.

=head1 CAUTIONS

After executing this command (and waiting for the Update Server to
propagate the changes, if it is used), restart the database server
processes on all database server machines to force election of a quorum
that includes the new set of machines listed in the
F</usr/afs/etc/CellServDB> file. The I<IBM AFS Quick Beginnings> explains
in more detail how to add and remove database server machines.

=head1 OPTIONS

=over 4

=item B<-server> <I<machine name>>

Indicates the server machine on which to change the
F</usr/afs/etc/CellServDB> file. Identify the machine by IP address or its
host name (either fully-qualified or abbreviated unambiguously). For
details, see L<bos(8)>.

In cells that use the Update Server to distribute the contents of the
F</usr/afs/etc> directory, it is conventional to specify only the system
control machine as a value for the B<-server> argument. Otherwise, repeat
the command for each file server machine. For further discussion, see
L<bos(8)>.

=item B<-host> <I<host name>>+

Specifies the fully-qualified host name (such as C<fs2.abc.com>) of each
database server machine to remove from the B<CellServDB> file.

=item B<-cell> <I<cell name>>

Names the cell in which to run the command. Do not combine this argument
with the B<-localauth> flag. For more details, see L<bos(8)>.

=item B<-noauth>

Assigns the unprivileged identity C<anonymous> to the issuer. Do not
combine this flag with the B<-localauth> flag. For more details, see
L<bos(8)>.

=item B<-localauth>

Constructs a server ticket using a key from the local
F</usr/afs/etc/KeyFile> file. The B<bos> command interpreter presents the
ticket to the BOS Server during mutual authentication. Do not combine this
flag with the B<-cell> or B<-noauth> options. For more details, see
L<bos(8)>.

=item B<-help>

Prints the online help for this command. All other valid options are
ignored.

=back

=head1 EXAMPLES

The following command removes the former database server machine
C<db2.abc.com> from the F<CellServDB> file on the system control machine
C<fs1.abc.com>.

   % bos removehost -server fs1.abc.com -host db2.abc.com

=head1 PRIVILEGE REQUIRED

The issuer must be listed in the F</usr/afs/etc/UserList> file on the
machine named by the B<-server> argument, or must be logged onto a server
machine as the local superuser C<root> if the B<-localauth> flag is
included.

=head1 SEE ALSO

L<KeyFile(5)>,
L<UserList(5)>,
L<bos(8)>,
L<bos_addhost(8)>,
L<bos_listhosts(8)>

I<IBM AFS Quick Beginnings>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
