=head1 NAME

kdb - Displays log or privileged actions performed by the Authentication Server

=head1 SYNOPSIS

B<kdb> [-dbmfile <I<dbmfile to use (default /usr/afs/logs/AuthLog)>>]  
[B<-key> <I<extract entries that match specified key>>]  [B<-help>]

=head1 DESCRIPTION

The kdb command displays the contents of the
B<AuthLog.dir> and B<AuthLog.pag> files
associated with the B<AuthLog> file that resides on the local disk, by
default in the B</usr/afs/logs> directory. The files must exist
in that directory, which normally implies that the Authentication Server is
running on the machine. The files contain information on privileged
actions performed by the Authentication Server.

=head1 CAVEATS

It is possible that on some operating systems that AFS otherwise supports,
the Authentication Server cannot create the
B</usr/afs/logs/AuthLog.dir> and
B</usr/afs/logs/AuthLog.pag> files, making this command
inoperative. See the I<IBM AFS Release Notes> for
details.

=head1 OPTIONS

=over 4

=item -dbmfile

Specifies the pathname of the file to display. Provide either a
complete pathname, a pathname relative to the B</usr/afs/logs>
directory, or a filename only, in which case the file must reside in the
B</usr/afs/logs> directory. Omit this argument to display
information from the B<AuthLog.dir> and
B<AuthLog.pag> files in the B</usr/afs/logs>
directory.

=item -key

Specifies each entry to be displayed from the indicated file.

=item -help

Prints the online help for this command. All other valid options
are ignored.

=back

=head1 OUTPUT

The first line of output indicates the location of the files from which the
subsequent information is derived:

   Printing all entries found in I<file_location>

Each entry then includes the following two fields, separated by a
colon:

=over 4

=item C<user/server
>

Identifies the user requesting the corresponding service and the server
that performed that service. In cases where no user is directly
involved, only the server appears; in cases where no server is directly
involved, only the user appears.

=item C<service
>

Identifies one of the following actions or services performed by the user
or server process. 

=over 4

=item *

C<auth>: Obtained a ticket-granting ticket


=item *

C<chp>: Changed a user password


=item *

C<cruser>: Created a user entry in the Authentication
Database


=item *

C<delu>: Deleted a user entry from the Authentication
Database


=item *

C<gtck>: Obtained a ticket other than a ticket-granting
ticket


=item *

C<setf>: Set fields in an Authentication Database entry


=item *

C<unlok>: Unlocked an Authentication Database entry


=back

=back

The final line of output sums the number of entries.

=head1 EXAMPLES

The following example shows the output of the kdb command in the
ABC Corporation cell (B<abc.com>):

   % kdb
   Printing all entries found in /usr/afs/logs/AuthLog
   admin,krbtgt.ABC.COM:auth
   admin,afs:gtck
   admin:cruser
   admin:delu
   4 entries were found

=head1 PRIVILEGE REQUIRED

The issuer must be logged in as the local superuser root.

=head1 SEE ALSO

L<AuthLog.dir,_AuthLog.pag(1)>,
L<bos_getlog(1)>,
L<kaserver(1)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
