=head1 NAME

volinfo - Produces detailed statistics about one or more volume headers and the
partition that houses them

=head1 SYNOPSIS

B<volinfo> [B<-online>]  [B<-vnode>]  [B<-date>]  [B<-inode>] [-itime]  
[B<-part>  <I<AFS partition name (default current partition)>>+]   
        [B<-volumeid> <I<Volume id>>+]  [B<-header>]  [B<-sizeOnly>]  [-fixheader]  
        [B<-saveinodes>]  [B<-orphaned>]  [-help]

=head1 DESCRIPTION

The volinfo command displays detailed statistics about one or
more volume headers and the partition that houses them. The command
must be issued on a file server machine and by default produces output for
every volume on every AFS server partition on the machine. To display
output for the volumes on one partition only, include the B<-part>
argument. To display output for one volume only, include the
B<-volumeid> argument.

=head1 OPTIONS

=over 4

=item -online

Is nonoperational.

=item -vnode

Displays a table for each volume which lists the large (directory) and
small (file) vnodes in it, in addition to the default output.

=item -date

When combined with the -vnode flag, adds the
C<ServerModTime> field to each vnode entry in the large vnode and
small vnode tables, reporting its most recent modification time.

=item -inode

When combined with the -vnode flag, adds the C<inode>
field to each vnode entry in the large vnode and small vnode tables, reporting
the associated inode number.

=item -itime

When combined with the -vnode flag, displays a change,
modification, and access timestamp for each of the large vnode and small vnode
tables.

=item -part

Specifies the partition that houses each volume for which to produce
output. Use the format B</vicep>I<xx>, where I<xx>
is one or two lowercase letters. This argument can be omitted if the
current working directory is the mount location for an AFS server
partition; it is not the mount location for an AFS server partition, the
command produces output for every volume on all local AFS server
partitions.

=item -volumeid

Specifies the ID number of one volume for which to produce output.
The B<-part> argument must be provided along with this one unless the
current working directory is the mount location for the AFS server partition
that houses the volume.

=item -header

Displays statistics about the volume header of each volume, in addition to
the default output.

=item -sizeOnly

Displays a single line of output for each volume, reporting the size of
various structures associated with it. The default output is suppressed
and any flags that modify it (such as B<-vnode>) are ignored.

=item -fixheader

Repairs damaged inodes in each volume if possible. If there are
any, it reports the action it is taking to repair them. Otherwise, it
produces no output in addition to the default output.

=item -saveinodes

Creates a file in the current working directory for each inode in each
volume. Each file is called
B<TmpInode.>I<vnode_number> and contains the inode's
contents. The default output is suppressed and any flags that modify it
(such as B<-vnode>) are ignored.

=item -orphaned

Displays a large vnode and small vnode table for each volume, which lists
only orphaned vnodes (vnodes that have no parent). If there are none,
the tables are empty (only the headers appear).

=item -help

Prints the online help for this command. All other valid options
are ignored.

=back

=head1 OUTPUT

By default, the command produces several line of statistics for each
volume. Adding other options produces or substitutes additional
information as described in the preceding B<Options> section of this
reference page. The output is intended for debugging purposes and is
meaningful to someone familiar with the internal structure of volume
headers.

=head1 PRIVILEGE REQUIRED

The issuer must be logged in as the local superuser root.

=head1 SEE ALSO

L<vldb.DB0 and vldb.DBSYS1(1)>

L<volserver(1)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
