#!/usr/bin/perl

use strict;
use warnings;
use File::Basename;
use lib "./tests-lib/perl5";
use mancheck_utils;

# Set this to the bare command to test
my $command = 'fs';
my $builddir = $ENV{C_TAP_BUILD};
if (!$builddir) {
    $builddir = dirname($0) . "/..";
}
$builddir .= "/..";
# Set this to the directory holding $command
my $srcdir = "$builddir/src/venus";

#---------------------------------------------------------------------

my @sub_commands = lookup_sub_commands($srcdir, $command);
plan tests => scalar @sub_commands;

test_command_man_pages($builddir, $command, @sub_commands);

