=head1 NAME

BackupLog - Traces Backup Server operations

=head1 DESCRIPTION

The F<BackupLog> file records a trace of Backup Server (B<buserver>
process) operations on the local machine and describes any error
conditions it encounters.

If the F<BackupLog> file does not already exist in the F</usr/afs/logs>
directory when the Backup Server starts, the server process creates it and
writes initial start-up messages to it. If there is an existing file, the
Backup Server renames it to F<BackupLog.old>, overwriting the existing
F<BackupLog.old> file if it exists.

The file is in ASCII format. Administrators listed in the
F</usr/afs/etc/UserList> file can use the B<bos getlog> command to display
its contents. Alternatively, log on to the machine and use a text editor
or a file display command such as the UNIX B<cat> command. By default, the
mode bits on the F<BackupLog> file grant the required C<r> (read)
permission to all users.

The Backup Server records operations only as it completes them, and so
cannot recover from failures by reviewing the file. The log contents are
useful for administrative evaluation of process failures and other
problems.

=head1 SEE ALSO

L<UserList(5)>,
L<bos_getlog(8)>,
L<buserver(8)>

=head1 COPYRIGHT

IBM Corporation 2000. <http://www.ibm.com/> All Rights Reserved.

This documentation is covered by the IBM Public License Version 1.0.  It was
converted from HTML to POD by software written by Chas Williams and Russ
Allbery, based on work by Alf Wachsmann and Elizabeth Cassell.
