Source: openafs
Section: net
Priority: optional
Maintainer: Sam Hartman <hartmans@debian.org>
Standards-Version: 3.1.1

Package: openafs-modules-=KVERS
Conflicts: openafs-client (<< 1.2.2-0)
Provides: openafs-modules1
Architecture: any
Description: The AFS distributed filesystem- Kernel Module
 AFS is a distributed filesystem allowing cross-platform sharing of
 files among multiple computers.  Facilities are provided for access
 control, authentication, backup and administrative management.
 .
 This package provides the kernel module for the filesystem
