#!/bin/sh
case `arch` in
i[3456]86)
	case $KVERS in
	    2.2*)
		echo i386_linux22
		;;
	    2.4*)
		echo i386_linux24
		;;
	    esac
;;
    ia64)
    echo ia64_linux24
;;
    alpha)
	case $KVERS in
	    2.2*)
		echo alpha_linux_22
		;;
	    2.4*)
		echo alpha_linux_24
		;;
	    esac
;;
    sparc)
	case $KVERS in
	    2.2*)
		echo sparc_linux22
		;;
	    2.4*)
		echo sparc_linux24
		;;
	    esac
	;;
    sparc64)
        case $KVERS in
	    2.2*)
		echo sparc64_linux22
		;;
	    2.4*)
		echo sparc64_linux24
		;;
	    esac
	;;
	    
    ppc)
	case $KVERS in
	    2.2*)
		echo ppc_linux22
		;;
	    2.4*)
		echo ppc_linux24
		;;
	    esac
	    ;;
	*)
	echo ERROr:  sysname not yet known
	exit 1

esac
