#!/bin/sh

set -e

# In version 1.6.3-1, we switched from symlinking the doc directory to
# openafs-client to having our own doc directory so that we could weaken the
# versioned dependency.  dpkg doesn't remove symlinks on upgrade, so we need
# to remove the symlink in preinst to avoid overwriting the old files.
#
# This cleanup can be removed after the jessie release.
test ! -L /usr/share/doc/openafs-dbserver \
    || rm /usr/share/doc/openafs-dbserver

#DEBHELPER#
