debian/tmp/usr/sbin/prdb_check          usr/sbin
debian/tmp/usr/sbin/pt_util             usr/sbin
debian/tmp/usr/sbin/vldb_check          usr/sbin

debian/afs-rootvol                      usr/sbin
debian/afs-newcell                      usr/sbin

debian/tmp/usr/lib/openafs/buserver     usr/lib/openafs
debian/tmp/usr/lib/openafs/ptserver     usr/lib/openafs
debian/tmp/usr/lib/openafs/vlserver     usr/lib/openafs

debian/ConfigUtils.pm                   usr/share/perl5/Debian/OpenAFS
