#! /bin/sh

set -e

# Purges the database and log files created by the package.  We assume that
# it's safe to do this for database files since they're normally transferred
# via Ubik to other hosts.
if [ "$1" = 'purge' ] ; then
    for file in prdb.DB0 prdb.DBSYS1 vldb.DB0 vldb.DBSYS1 ; do
        rm -f "/var/lib/openafs/db/$file"
    done
    for file in PtLog PtLog.old VLLog VLLog.old ; do
        rm -f "/var/log/openafs/$file"
    done
fi

#DEBHELPER#
