#!/bin/sh
case `arch` in
    alpha)
	echo alpha_linux_22
	;;
i[3456]86)
	echo i386_linux24
;;
    ia64)
    echo ia64_linux24
;;
    parisc*)
	echo parisc_linux24
	;;
    ppc)
	echo ppc_linux24
	;;
    sparc|sparc64)
	echo sparc_linux24
	;;
    s390)
    echo s390_linux24
    ;;
	*)
	echo ERROr:  sysname not yet known
	exit 1

esac
