# Keep macros within each section in sorted order for clean diff displays.
# AFS_OSTYPE used to indicate suffixes and os specific subdirectories.
AFS_OSTYPE = NCR

# compilation and link editor flags
#
# libraries
#
# programs
AR = /usr/ccs/bin/ar
LD = /usr/ccs/bin/ld
LORDER = /usr/ccs/bin/lorder
STRIP= /usr/ccs/bin/strip
