# Copyright 2006, Sine Nomine Associates and others.
# All Rights Reserved.
# 
# This software has been released under the terms of the IBM Public
# License.  For details, see the LICENSE file in the top-level source
# directory or online at http://www.openafs.org/dl/license10.html


# build common variable interfaces
LIBTRACE_CFLAGS = \
	$(LIBTRACE_CFLAGS_COMMON) \
	$(LIBTRACE_CFLAGS_$(LIBTRACE_BULDING_MODE)) \
	$(LIBTRACE_CFLAGS_$(LIBTRACE_BUILDING)) \
	$(NULL)
LIBTRACE_OBJS = \
	$(LIBTRACE_OBJS_COMMON) \
	$(LIBTRACE_OBJS_$(LIBTRACE_BUILDING_MODE)) \
	$(LIBTRACE_OBJS_$(LIBTRACE_BUILDING)) \
	$(NULL)
LIBTRACE_OS_CFLAGS = \
	$(LIBTRACE_OS_CFLAGS_COMMON) \
	$(LIBTRACE_OS_CFLAGS_$(LIBTRACE_BUILDING_MODE)) \
	$(LIBTRACE_OS_CFLAGS_$(LIBTRACE_BUILDING)) \
	$(NULL)
LIBTRACE_OS_OBJS = \
	$(LIBTRACE_OS_OBJS_COMMON) \
	$(LIBTRACE_OS_OBJS_$(LIBTRACE_BUILDING_MODE)) \
	$(LIBTRACE_OS_OBJS_$(LIBTRACE_BUILDING)) \
	$(NULL)


LIBTRACE_BIT_CFLAGS = \
	$(LIBTRACE_CFLAGS_COMMON_$(LIBTRACE_BUILDING_BIT)) \
	$(LIBTRACE_CFLAGS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_BIT)) \
	$(LIBTRACE_CFLAGS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_BIT)) \
	$(NULL)
LIBTRACE_BIT_OBJS = \
	$(LIBTRACE_OBJS_COMMON_$(LIBTRACE_BUILDING_BIT)) \
	$(LIBTRACE_OBJS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_BIT)) \
	$(LIBTRACE_OBJS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_BIT)) \
	$(NULL)
LIBTRACE_OS_BIT_CFLAGS = \
	$(LIBTRACE_OS_CFLAGS_COMMON_$(LIBTRACE_BUILDING_BIT)) \
	$(LIBTRACE_OS_CFLAGS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_BIT)) \
	$(LIBTRACE_OS_CFLAGS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_BIT)) \
	$(NULL)
LIBTRACE_OS_BIT_OBJS = \
	$(LIBTRACE_OS_OBJS_COMMON_$(LIBTRACE_BUILDING_BIT)) \
	$(LIBTRACE_OS_OBJS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_BIT)) \
	$(LIBTRACE_OS_OBJS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_BIT)) \
	$(NULL)


LIBTRACE_THR_CFLAGS = \
	$(LIBTRACE_CFLAGS_COMMON_$(LIBTRACE_BUILDING_THR)) \
	$(LIBTRACE_CFLAGS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_THR)) \
	$(LIBTRACE_CFLAGS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_THR)) \
	$(NULL)
LIBTRACE_THR_OBJS = \
	$(LIBTRACE_OBJS_COMMON_$(LIBTRACE_BUILDING_THR)) \
	$(LIBTRACE_OBJS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_THR)) \
	$(LIBTRACE_OBJS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_THR)) \
	$(NULL)
LIBTRACE_OS_THR_CFLAGS = \
	$(LIBTRACE_OS_CFLAGS_COMMON_$(LIBTRACE_BUILDING_THR)) \
	$(LIBTRACE_OS_CFLAGS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_THR)) \
	$(LIBTRACE_OS_CFLAGS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_THR)) \
	$(NULL)
LIBTRACE_OS_THR_OBJS = \
	$(LIBTRACE_OS_OBJS_COMMON_$(LIBTRACE_BUILDING_THR)) \
	$(LIBTRACE_OS_OBJS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_THR)) \
	$(LIBTRACE_OS_OBJS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_THR)) \
	$(NULL)

LIBTRACE_LIB_CFLAGS = \
	$(LIBTRACE_CFLAGS_COMMON_$(LIBTRACE_BUILDING_LIB)) \
	$(LIBTRACE_CFLAGS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_LIB)) \
	$(LIBTRACE_CFLAGS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_LIB)) \
	$(NULL)
LIBTRACE_LIB_OBJS = \
	$(LIBTRACE_OBJS_COMMON_$(LIBTRACE_BUILDING_LIB)) \
	$(LIBTRACE_OBJS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_LIB)) \
	$(LIBTRACE_OBJS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_LIB)) \
	$(NULL)
LIBTRACE_OS_LIB_CFLAGS = \
	$(LIBTRACE_OS_CFLAGS_COMMON_$(LIBTRACE_BUILDING_LIB)) \
	$(LIBTRACE_OS_CFLAGS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_LIB)) \
	$(LIBTRACE_OS_CFLAGS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_LIB)) \
	$(NULL)
LIBTRACE_OS_LIB_OBJS = \
	$(LIBTRACE_OS_OBJS_COMMON_$(LIBTRACE_BUILDING_LIB)) \
	$(LIBTRACE_OS_OBJS_$(LIBTRACE_BUILDING_MODE)_$(LIBTRACE_BUILDING_LIB)) \
	$(LIBTRACE_OS_OBJS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_LIB)) \
	$(NULL)



# final build targets
LIBTRACE_ALL_OBJS = \
	$(LIBTRACE_OBJS) \
	$(LIBTRACE_OS_OBJS) \
	$(LIBTRACE_BIT_OBJS) \
	$(LIBTRACE_OS_BIT_OBJS) \
	$(LIBTRACE_THR_OBJS) \
	$(LIBTRACE_OS_THR_OBJS) \
	$(LIBTRACE_LIB_OBJS) \
	$(LIBTRACE_OS_LIB_OBJS) \
	$(NULL)

LIBTRACE_ALL_CFLAGS = \
	$(LIBTRACE_CFLAGS) \
	$(LIBTRACE_OS_CFLAGS) \
	$(LIBTRACE_BIT_CFLAGS) \
	$(LIBTRACE_OS_BIT_CFLAGS) \
	$(LIBTRACE_THR_CFLAGS) \
	$(LIBTRACE_OS_THR_CFLAGS) \
	$(LIBTRACE_LIB_CFLAGS) \
	$(LIBTRACE_OS_LIB_CFLAGS) \
	$(NULL)

LIBTRACE_DEPS = \
	$(LIBTRACE_DEPS_$(LIBTRACE_BUILDING)_$(LIBTRACE_BUILDING_LIB)_$(LIBTRACE_BUILDING_THR)) \
	$(NULL)
