# Copyright 2006-2007, Sine Nomine Associates and others.
# All Rights Reserved.
# 
# This software has been released under the terms of the IBM Public
# License.  For details, see the LICENSE file in the top-level source
# directory or online at http://www.openafs.org/dl/license10.html


# build common variable interfaces
LIBAFSRPC_CFLAGS = \
	$(LIBAFSRPC_CFLAGS_COMMON) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BULDING_MODE)) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BUILDING)) \
	$(NULL)
LIBAFSRPC_OBJS = \
	$(LIBAFSRPC_OBJS_COMMON) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING_MODE)) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING)) \
	$(NULL)
LIBAFSRPC_OS_CFLAGS = \
	$(LIBAFSRPC_OS_CFLAGS_COMMON) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING_MODE)) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING)) \
	$(NULL)
LIBAFSRPC_OS_OBJS = \
	$(LIBAFSRPC_OS_OBJS_COMMON) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING_MODE)) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING)) \
	$(NULL)


LIBAFSRPC_BIT_CFLAGS = \
	$(LIBAFSRPC_CFLAGS_COMMON_$(LIBAFSRPC_BUILDING_BIT)) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_BIT)) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_BIT)) \
	$(NULL)
LIBAFSRPC_BIT_OBJS = \
	$(LIBAFSRPC_OBJS_COMMON_$(LIBAFSRPC_BUILDING_BIT)) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_BIT)) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_BIT)) \
	$(NULL)
LIBAFSRPC_OS_BIT_CFLAGS = \
	$(LIBAFSRPC_OS_CFLAGS_COMMON_$(LIBAFSRPC_BUILDING_BIT)) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_BIT)) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_BIT)) \
	$(NULL)
LIBAFSRPC_OS_BIT_OBJS = \
	$(LIBAFSRPC_OS_OBJS_COMMON_$(LIBAFSRPC_BUILDING_BIT)) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_BIT)) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_BIT)) \
	$(NULL)


LIBAFSRPC_INST_CFLAGS = \
	$(LIBAFSRPC_CFLAGS_COMMON_$(LIBAFSRPC_BUILDING_INST)) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_INST)) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_INST)) \
	$(NULL)
LIBAFSRPC_INST_OBJS = \
	$(LIBAFSRPC_OBJS_COMMON_$(LIBAFSRPC_BUILDING_INST)) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_INST)) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_INST)) \
	$(NULL)
LIBAFSRPC_OS_INST_CFLAGS = \
	$(LIBAFSRPC_OS_CFLAGS_COMMON_$(LIBAFSRPC_BUILDING_INST)) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_INST)) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_INST)) \
	$(NULL)
LIBAFSRPC_OS_INST_OBJS = \
	$(LIBAFSRPC_OS_OBJS_COMMON_$(LIBAFSRPC_BUILDING_INST)) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_INST)) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_INST)) \
	$(NULL)

LIBAFSRPC_THR_CFLAGS = \
	$(LIBAFSRPC_CFLAGS_COMMON_$(LIBAFSRPC_BUILDING_THR)) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_THR)) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_THR)) \
	$(NULL)
LIBAFSRPC_THR_OBJS = \
	$(LIBAFSRPC_OBJS_COMMON_$(LIBAFSRPC_BUILDING_THR)) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_THR)) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_THR)) \
	$(NULL)
LIBAFSRPC_OS_THR_CFLAGS = \
	$(LIBAFSRPC_OS_CFLAGS_COMMON_$(LIBAFSRPC_BUILDING_THR)) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_THR)) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_THR)) \
	$(NULL)
LIBAFSRPC_OS_THR_OBJS = \
	$(LIBAFSRPC_OS_OBJS_COMMON_$(LIBAFSRPC_BUILDING_THR)) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_THR)) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_THR)) \
	$(NULL)

LIBAFSRPC_LIB_CFLAGS = \
	$(LIBAFSRPC_CFLAGS_COMMON_$(LIBAFSRPC_BUILDING_LIB)) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_LIB)) \
	$(LIBAFSRPC_CFLAGS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_LIB)) \
	$(NULL)
LIBAFSRPC_LIB_OBJS = \
	$(LIBAFSRPC_OBJS_COMMON_$(LIBAFSRPC_BUILDING_LIB)) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_LIB)) \
	$(LIBAFSRPC_OBJS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_LIB)) \
	$(NULL)
LIBAFSRPC_OS_LIB_CFLAGS = \
	$(LIBAFSRPC_OS_CFLAGS_COMMON_$(LIBAFSRPC_BUILDING_LIB)) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_LIB)) \
	$(LIBAFSRPC_OS_CFLAGS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_LIB)) \
	$(NULL)
LIBAFSRPC_OS_LIB_OBJS = \
	$(LIBAFSRPC_OS_OBJS_COMMON_$(LIBAFSRPC_BUILDING_LIB)) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING_MODE)_$(LIBAFSRPC_BUILDING_LIB)) \
	$(LIBAFSRPC_OS_OBJS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_LIB)) \
	$(NULL)



# final build targets
LIBAFSRPC_ALL_OBJS = \
	$(LIBAFSRPC_OBJS) \
	$(LIBAFSRPC_OS_OBJS) \
	$(LIBAFSRPC_BIT_OBJS) \
	$(LIBAFSRPC_OS_BIT_OBJS) \
	$(LIBAFSRPC_INST_OBJS) \
	$(LIBAFSRPC_OS_INST_OBJS) \
	$(LIBAFSRPC_THR_OBJS) \
	$(LIBAFSRPC_OS_THR_OBJS) \
	$(LIBAFSRPC_LIB_OBJS) \
	$(LIBAFSRPC_OS_LIB_OBJS) \
	$(NULL)

LIBAFSRPC_ALL_CFLAGS = \
	$(LIBAFSRPC_CFLAGS) \
	$(LIBAFSRPC_OS_CFLAGS) \
	$(LIBAFSRPC_BIT_CFLAGS) \
	$(LIBAFSRPC_OS_BIT_CFLAGS) \
	$(LIBAFSRPC_INST_CFLAGS) \
	$(LIBAFSRPC_OS_INST_CFLAGS) \
	$(LIBAFSRPC_THR_CFLAGS) \
	$(LIBAFSRPC_OS_THR_CFLAGS) \
	$(LIBAFSRPC_LIB_CFLAGS) \
	$(LIBAFSRPC_OS_LIB_CFLAGS) \
	$(NULL)

LIBAFSRPC_DEPS = \
	$(LIBAFSRPC_DEPS_$(LIBAFSRPC_BUILDING)_$(LIBAFSRPC_BUILDING_LIB)_$(LIBAFSRPC_BUILDING_THR)_$(LIBAFSRPC_BUILDING_INST)_$(LIBAFSRPC_BUILDING_BIT)) \
	$(NULL)
