@CD src\WINNT\install\NSIS 
echo Directory - src\WINNT\install\NSIS 
@CD src\config
echo Directory - src\config
echo Directory - src\config
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_cpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_config
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_cpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_config
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_cpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_config
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_exp
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_cpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_config
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_exp
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_creds
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_cpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_config
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_exp
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_creds
echo Directory - c:\src\openafs\openafs-cvs\src\finale
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_cpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_config
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_exp
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_creds
echo Directory - c:\src\openafs\openafs-cvs\src\finale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\install\NSIS
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\install\NSIS
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\install\NSIS
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\install\NSIS
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\install\NSIS
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\install\NSIS
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\install\NSIS
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\install\NSIS
echo Directory - c:\src\openafs\openafs-cvs\src\config
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\util
echo Directory - c:\src\openafs\openafs-cvs\src\comerr
echo Directory - c:\src\openafs\openafs-cvs\src\afs
echo Directory - c:\src\openafs\openafs-cvs\src\cmd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsreg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\eventlog
echo Directory - c:\src\openafs\openafs-cvs\src\lwp
echo Directory - c:\src\openafs\openafs-cvs\src\rxgen
echo Directory - c:\src\openafs\openafs-cvs\src\des
echo Directory - c:\src\openafs\openafs-cvs\src\rx
echo Directory - c:\src\openafs\openafs-cvs\src\rxstat
echo Directory - c:\src\openafs\openafs-cvs\src\rxkad
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\pthread
echo Directory - c:\src\openafs\openafs-cvs\src\procmgmt
echo Directory - c:\src\openafs\openafs-cvs\src\fsint
echo Directory - c:\src\openafs\openafs-cvs\src\audit
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\sys
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\auth
echo Directory - c:\src\openafs\openafs-cvs\src\ubik
echo Directory - c:\src\openafs\openafs-cvs\src\ptserver
echo Directory - c:\src\openafs\openafs-cvs\src\libacl
echo Directory - c:\src\openafs\openafs-cvs\src\kauth
echo Directory - c:\src\openafs\openafs-cvs\src\vlserver
echo Directory - c:\src\openafs\openafs-cvs\src\usd
echo Directory - c:\src\openafs\openafs-cvs\src\bubasics
echo Directory - c:\src\openafs\openafs-cvs\src\budb
echo Directory - c:\src\openafs\openafs-cvs\src\butm
echo Directory - c:\src\openafs\openafs-cvs\src\dir
echo Directory - c:\src\openafs\openafs-cvs\src\vol
echo Directory - c:\src\openafs\openafs-cvs\src\volser
echo Directory - c:\src\openafs\openafs-cvs\src\viced
echo Directory - c:\src\openafs\openafs-cvs\src\update
echo Directory - c:\src\openafs\openafs-cvs\src\bucoord
echo Directory - c:\src\openafs\openafs-cvs\src\butc
echo Directory - c:\src\openafs\openafs-cvs\src\bozo
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\bosctlsvc
echo Directory - c:\src\openafs\openafs-cvs\src\bu_utils
echo Directory - c:\src\openafs\openafs-cvs\src\libafsrpc
echo Directory - c:\src\openafs\openafs-cvs\src\libafsauthent
echo Directory - c:\src\openafs\openafs-cvs\src\tviced
echo Directory - c:\src\openafs\openafs-cvs\src\tbutc
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\adminutil
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\vos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\client
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\kas
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\pts
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\bos
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\cfg
echo Directory - c:\src\openafs\openafs-cvs\src\libadmin\test
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\license
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsadmsvr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsusrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrmgr
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcfg
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afssvrcpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\talocale
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_osi
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\afsd
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_cpa
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_config
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_exp
echo Directory - c:\src\openafs\openafs-cvs\src\WINNT\client_creds
echo Directory - c:\src\openafs\openafs-cvs\src\finale
