#!/bin/sh
#
# This software has been released under the terms of the IBM Public
# License.  For details, see the LICENSE file in the top-level source
# directory or online at http://www.openafs.org/dl/license10.html
#
# This file (software) may also be used separately from OpenAFS
# under other licenses, contact the author(s) listed below for details.
#
# copyright 2011, 2012 Troy Benjegerdes <hozer@hozed.org>

. tap/libtap.sh


plan 1


grep -e "^>" fuse/conf/CellServDB  | cut -d " " -f 1 | cut -b2- | sort > fuse/cells.tmp

(cd fuse; ./try-fuse.sh > ./fuse-log 2>&1 ) &

fusepid=$!

sleep 1
ls fuse/mntdir | sort > fuse/ls.tmp
ok "ls dynroot" diff fuse/cells.tmp fuse/ls.tmp

rm fuse/cells.tmp fuse/ls.tmp

#not the best way to handle this
killall afsd.fuse

wait
